version: '3.8'
services:
  web:
    container_name: nginx-container
    build: ./config/nginx
    ports:
      - "80:80"
    volumes:
      - ./files/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo
    networks:
      php-dev-network:
        ipv4_address: 192.168.200.101
  php:
    container_name: php-container
    build: ./config/php
    volumes:
      - ./volumes/source/:/var/source/
      - ./files/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - TZ=Asia/Tokyo
    networks:
      php-dev-network:
        ipv4_address: 192.168.200.102
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  db:
    container_name: mysql-container
    build: ./config/mysql
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=passwd
      - TZ=Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      php-dev-network:
        ipv4_address: 192.168.200.103
  redis:
    container_name: redis-container
    build: ./config/redis
    ports:
      - 6379:6379
    networks:
      php-dev-network:
        ipv4_address: 192.168.200.104
networks:
  php-dev-network:
    name: php-dev-network
    driver: bridge
    ipam:
      config: 
        - subnet: 192.168.200.0/24
